# Generated by Django 3.2.3 on 2021-09-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='date',
            field=models.DateField(default='04-09-2021'),
        ),
    ]
