# Generated by Django 3.2.3 on 2021-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_itemmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='date',
            field=models.DateField(default='04-09-2021', null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='quantity',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
