# Generated by Django 3.2.3 on 2021-09-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210905_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
